### ISSUE TITLE
Error from uploading multiple files

### ISSUE THREAD

**Issue by anniekj** [dibbs-vdc/ccql#34] opened 2017-10-26 14:29 UTC
I tried to upload 6 files (total: 6.7 MB) and got an error (see attached). I tried this two more times and continued to get an error message. Then when I went back to my dashboard, all the files had been successfully uploaded, 3x. 
![vdcerror](https://user-images.githubusercontent.com/19959643/32058886-83535c8c-ba38-11e7-9193-d5ca39611fb7.jpg)

**Comment by jkim-ru** [comment] 2017-11-03 20:10
Would you be able to send me the files that caused this behavior?  Please send them via email or send me links to them if you have them. I want to try to reproduce in my local dev environment. Thanks!

**Comment by anniekj** [comment] 2017-11-06 14:14
Here are the files:
https://zenodo.org/record/55295#.WgBuGoZrzq0

**Comment by jkim-ru** [comment] 2017-11-06 19:33
I tried to reproduce in my local dev environment, and I had no problems.  However, when I tried on the shared dev machine, I was able to reproduce the error. I watched the logs while I attempted to create a resource with the 6 files that Annie pointed me to. The transaction appeared to complete successfully in the logs. 

I've seen this error before on the shared dev machine, and it seems like it appears when a transaction takes a long time to process. I may not see it on my local dev machine because I am not using apache.

Potentially related issue:
https://serverfault.com/questions/185894/proxy-error-502-reason-error-reading-from-remote-server-with-apache-2-2-3-de

**Comment by jkim-ru** [comment] 2017-11-06 20:52
We modified the Apache configuration with the following line:

ProxyTimeout 600

The error doesn't happen anymore.  Because this is a prototype system running on a development environment, this is okay for now. I'm going to close this ticket, but feel free to open it again if you need more than 10 minutes (600 seconds) to process a file.

**Closed by jkim-ru** 2017-11-06 20:52 UTC
Labels: bug, Work In Progress
